export const pacotes = [
    { 
        id: 1, 
        nome: "Rio de Janeiro - Carnaval", 
        destino: "Rio de Janeiro, RJ", 
        data: "10/02/2025", 
        preco: 1200,
        descricao: "Pacote completo para o carnaval no Rio de Janeiro, com ingressos para os desfiles das escolas de samba.",
        duracao: "7 dias",
        localPartida: "São Paulo, SP",
        quantidadeLugares: 50,
        imagem: "rio.jpeg"
    },
    { 
        id: 2, 
        nome: "Fernando de Noronha - Paraíso Natural", 
        destino: "Pernambuco", 
        data: "15/03/2025", 
        preco: 3500,
        descricao: "Descubra as praias paradisíacas de Fernando de Noronha com pacotes que incluem passeios de barco e snorkel.",
        duracao: "5 dias",
        localPartida: "Recife, PE",
        quantidadeLugares: 30,
        imagem: "fernando.jpeg"

    },
    { 
        id: 3, 
        nome: "Gramado - Natal Luz", 
        destino: "Rio Grande do Sul", 
        data: "10/12/2025", 
        preco: 2000,
        descricao: "A magia do Natal no sul do Brasil, com decorações temáticas e atrações especiais para a família.",
        duracao: "6 dias",
        localPartida: "Porto Alegre, RS",
        quantidadeLugares: 40,
        imagem: "gramado.jpeg"
    },
    { 
        id: 4, 
        nome: "Bonito - Ecoturismo", 
        destino: "Mato Grosso do Sul", 
        data: "20/06/2025", 
        preco: 1800,
        descricao: "Pacote para quem busca aventuras na natureza, com visitas a cavernas, rios cristalinos e cachoeiras.",
        duracao: "5 dias",
        localPartida: "Campo Grande, MS",
        quantidadeLugares: 25,
        imagem: "bonito.jpeg"
    },
    { 
        id: 5, 
        nome: "Amazônia - Expedição Fluvial", 
        destino: "Manaus, AM", 
        data: "05/07/2025", 
        preco: 2800,
        descricao: "Aventuras de barco pela maior floresta tropical do mundo, com visitas a comunidades ribeirinhas e fauna exótica.",
        duracao: "7 dias",
        localPartida: "Manaus, AM",
        quantidadeLugares: 20,
        imagem: "amazonia.jpeg"
    },
    { 
        id: 6, 
        nome: "Lençóis Maranhenses - Aventura", 
        destino: "Maranhão", 
        data: "12/08/2025", 
        preco: 2200,
        descricao: "Uma expedição aos Lençóis Maranhenses, com passeios pelas dunas e lagoas cristalinas.",
        duracao: "6 dias",
        localPartida: "São Luís, MA",
        quantidadeLugares: 35,
        imagem: "maranhao.jpeg"
    },
    { 
        id: 7, 
        nome: "Buenos Aires - Cultura e Gastronomia", 
        destino: "Argentina", 
        data: "05/05/2025", 
        preco: 2200,
        descricao: "Explore a capital argentina com tours culturais e degustações de vinhos e pratos típicos da culinária local.",
        duracao: "5 dias",
        localPartida: "São Paulo, SP",
        quantidadeLugares: 45,
        imagem: "bueno.jpeg"
    },
    { 
        id: 8, 
        nome: "Orlando - Parques Temáticos", 
        destino: "EUA", 
        data: "15/06/2025", 
        preco: 5000,
        descricao: "Pacote para os amantes de diversão nos famosos parques de Orlando, incluindo ingressos para Disney e Universal Studios.",
        duracao: "8 dias",
        localPartida: "São Paulo, SP",
        quantidadeLugares: 60,
        imagem: "orlando.jpeg"
    },
    { 
        id: 9, 
        nome: "Paris - Cidade Luz", 
        destino: "França", 
        data: "25/09/2025", 
        preco: 7000,
        descricao: "Explore a arte, cultura e gastronomia de Paris, incluindo passeios pelos principais pontos turísticos e museus.",
        duracao: "6 dias",
        localPartida: "Rio de Janeiro, RJ",
        quantidadeLugares: 30,
        imagem: "paris.jpeg"
    },
    { 
        id: 10, 
        nome: "Tóquio - Tecnologia e Tradição", 
        destino: "Japão", 
        data: "10/11/2025", 
        preco: 8000,
        descricao: "Vivencie a fusão entre o moderno e o tradicional em Tóquio, com visitas a templos e experiências futuristas.",
        duracao: "7 dias",
        localPartida: "São Paulo, SP",
        quantidadeLugares: 15,
        imagem: "toquio.jpeg"
    },
    { 
        id: 11, 
        nome: "Barcelona - História e Cultura", 
        destino: "Espanha", 
        data: "03/08/2025", 
        preco: 4500,
        descricao: "Descubra a rica história de Barcelona com passeios pela arquitetura de Gaudí e pelas praias da cidade.",
        duracao: "6 dias",
        localPartida: "São Paulo, SP",
        quantidadeLugares: 25,
        imagem: "barcelona.jpeg"
    },
    { 
        id: 12, 
        nome: "Cancún - Paraíso Caribenho", 
        destino: "México", 
        data: "18/07/2025", 
        preco: 3500,
        descricao: "Relaxe nas praias de águas cristalinas e explore as ruínas maias em Cancún.",
        duracao: "7 dias",
        localPartida: "São Paulo, SP",
        quantidadeLugares: 40,
        imagem: "cancun.jpeg"
    },
    { 
        id: 13, 
        nome: "Lisboa - Passeios Europeus", 
        destino: "Portugal", 
        data: "01/10/2025", 
        preco: 4000,
        descricao: "Aproveite os encantos de Lisboa, com passeios por bairros históricos, museus e ótimos restaurantes.",
        duracao: "5 dias",
        localPartida: "São Paulo, SP",
        quantidadeLugares: 20,
        imagem: "lisboa.jpeg"
    },
    { 
        id: 14, 
        nome: "Dubai - Luxo e Aventura", 
        destino: "Emirados Árabes", 
        data: "12/02/2025", 
        preco: 10000,
        descricao: "Explore o luxo de Dubai com visitas ao Burj Khalifa, safáris no deserto e compras nos shoppings mais luxuosos.",
        duracao: "6 dias",
        localPartida: "São Paulo, SP",
        quantidadeLugares: 30,
        imagem: "dubai.jpeg"
    },
    { 
        id: 15, 
        nome: "Machu Picchu - Aventura Andina", 
        destino: "Peru", 
        data: "30/06/2025", 
        preco: 5000,
        descricao: "Uma jornada até Machu Picchu, com visitas a vilarejos andinos e trilhas históricas.",
        duracao: "8 dias",
        localPartida: "Lima, Peru",
        quantidadeLugares: 25,
        imagem: "machu.jpeg"
    }
]